---
_extends: .github

repository:
  name: c-toxcore
  description: The future of online communications.
  homepage: https://tox.chat/
  topics: toxcore, network, p2p, security, encryption, cryptography

branches:
  - name: "master"
    protection:
      required_status_checks:
        contexts:
          - "analysis (autotools)"
          - "analysis (clang-tidy)"
          - "analysis (compcert)"
          - "analysis (cppcheck)"
          - "analysis (doxygen)"
          - "analysis (misra)"
          - "analysis (tcc)"
          - "analysis (tokstyle)"
          - "bazel-dbg"
          - "bazel-opt"
          - "build-android"
          - "build-macos"
          - "build-windows (32)"
          - "build-windows (64)"
          - "ci/circleci: asan"
          - "ci/circleci: bazel-asan"
          - "ci/circleci: bazel-msan"
          - "ci/circleci: bazel-tsan"
          - "ci/circleci: clang-analyze"
          - "ci/circleci: cpplint"
          - "ci/circleci: infer"
          - "ci/circleci: static-analysis"
          - "ci/circleci: tsan"
          - "ci/circleci: ubsan"
          - "cimple"
          - "cimplefmt"
          - "CodeFactor"
          - "code-review/reviewable"
          - "common / buildifier"
          - "coverage-linux"
          - "docker-bootstrap-node"
          - "docker-bootstrap-node-websocket"
          - "docker-clusterfuzz"
          - "docker-esp32"
          - "docker-fuzzer"
          - "docker-toxcore-js"
          - "docker-win32"
          - "docker-win64"
          - "freebsd"
          - "Hound"
          - "mypy"
          - "program-analysis"
          - "sonar-scan"
          - "TokTok.c-toxcore"
          - "TokTok.c-toxcore (windows_msvc_conan shared)"
          - "TokTok.c-toxcore (windows_msvc_conan static)"

# Labels specific to c-toxcore.
labels:
  - name: "bootstrap"
    color: "#01707f"
    description: "Bootstrap"

  - name: "crypto"
    color: "#1d76db"
    description: "Crypto"

  - name: "file transfers"
    color: "#e02abf"
    description: "File Transfers"

  - name: "messenger"
    color: "#d93f0b"
    description: "Messenger"

  - name: "network"
    color: "#d4c5f9"
    description: "Network"

  - name: "toxav"
    color: "#0052cc"
    description: "Audio/video"
