---
cache:
  - '%USERPROFILE%\.conan'

install:
  - set PATH=C:\Python38-x64\Scripts;%PATH%
  - py -3 -m pip install conan

before_build:
  - conan install -if _build .

build_script:
  - conan build -bf _build -if _build .

test_script:
  - set CONAN_CPU_COUNT=50
  - set CTEST_OUTPUT_ON_FAILURE=1
  - conan install -if _build -o with_tests=True .
  - conan build -bf _build -if _build . &
    exit 0
