[build]
command = """\
  if cd doxygen-awesome-css; then \
    git pull --rebase && cd ..; \
  else \
    git clone --depth=1 https://github.com/jothepro/doxygen-awesome-css;
  fi && \
  doxygen docs/Doxyfile \
  """
publish = "_docs/html"
