name: ci

on:
  pull_request:
    branches: [master]

jobs:
  build-nacl:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Docker Build
        uses: docker/build-push-action@v2
        with:
          file: other/docker/autotools/Dockerfile

  build-win32:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - uses: actions/checkout@v2
      - name: Docker Build
        run: .travis/cmake-win32 install
      - name: Cross compilation
        run: .travis/cmake-win32 script

  build-win64:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - uses: actions/checkout@v2
      - name: Docker Build
        run: .travis/cmake-win64 install
      - name: Cross compilation
        run: .travis/cmake-win64 script

  build-freebsd:
    runs-on: ubuntu-latest
    container: toxchat/freebsd
    steps:
      - uses: actions/checkout@v2
      - name: Build on FreeBSD
        run: .travis/cmake-freebsd-stage2

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and test
        run: .travis/cmake-osx
