name: post-submit

on:
  push:
    branches: [master]

jobs:
  build-alpine-s390x:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Docker Build
        uses: docker/build-push-action@v4
        with:
          file: other/docker/alpine-s390x/Dockerfile

  docker-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker
      - name: Login to DockerHub
        if: ${{ github.event_name == 'push' }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build toxchat/c-toxcore:sources
        uses: docker/build-push-action@v4
        with:
          file: other/docker/sources/sources.Dockerfile
          tags: toxchat/c-toxcore:sources
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          file: other/docker/coverage/coverage.Dockerfile
          push: ${{ github.event_name == 'push' }}
          tags: toxchat/c-toxcore:coverage
          cache-from: type=registry,ref=toxchat/c-toxcore:coverage
          cache-to: type=inline
